### ISSUE TITLE
units for survey indices - numbers or biomass?

### ISSUE THREAD

**Issue by gavinfay** [gavinfay/bsb-ss-2022#29]
Hi @jmcnamee @lidach @kcurti @samtruesdell,
Wanting to check on the units for the black sea bass indices.
Which are based on numbers, and which (if any) are on biomass (e.g. kg per tow)?
If this is tracked somewhere please feel free to point me to it - I did some looking and was able to garner a few from various data summaries / standardization presentations that Sam has shared, but figured it would be easy to just ask.
Thanks!

**Comment by samtruesdell** [comment]
Hi Gavin -- the index work I did was based on numbers only; I think this was true for @kcurti too but she can correct me if otherwise!
