### ISSUE TITLE
Problem when excluding N sizefreq methods (inch based rec discards)

### ISSUE THREAD

**Issue by lidach** [gavinfay/bsb-ss-2022#30]
So when I read in the ss files that's on the current repo, I get this error in the terminal "Incompatible array bounds in dmatrix(int nrl, int nrh, int ncl, const ivector& nch)". When I look into the echoinput, it for some reason cannot read the "0" for the N sizefreq methods and reads it as "-230683617 N sizefreq methods to read". 

@jmcnamee @gavinfay any idea why this is happening?

**Comment by gavinfay** [comment]
@lidach are you still having this problem?

**Comment by lidach** [comment]
@gavinfay Yeah I'm still having the issue, I've just been putting the size data again.

I looked in the echoinput and compared between the two and I can't find anything different.
